kind: Pod
apiVersion: v1
spec:
  serviceAccount: terraform-builder-sa
  containers:
    - name: python
      image: python:3.13
      tty: true
      command:
        - cat
    - name: nodejs
      image: node:23.11.0
      tty: true
      command:
        - cat
    - name: terraform
      image: europe-west1-docker.pkg.dev/internal-services-prod-453c/mpb-docker-mutable/terraform
      tty: true
      command:
        - cat
    - name: docker
      image: docker:latest
      tty: true
      command:
        - cat
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2376
        - name: DOCKER_CERT_PATH
          value: "/certs/client"
        - name: DOCKER_TLS_VERIFY
          value: "1"
      volumeMounts:
        - name: dind-cert-client-storage
          mountPath: /certs/client
    - name: docker-daemon
      image: docker:dind
      env:
        - name: DOCKER_TLS_CERTDIR
          value: "/certs"
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
        - name: dind-cert-client-storage
          mountPath: /certs/client
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-cert-client-storage
      emptyDir: {}