version: '3.8'
services:
  search-backend:
    build: .
    container_name: search-backend
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
    volumes:
      - ./src:/app
    restart: unless-stopped