services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      FLASK_APP: '/mpb/src/app.py'
      FLASK_DEBUG: 1
      FLASK_RUN_PORT: 8080
      LLM_PRODUCT: 'placeholder'
      PYTHONPATH: '/mpb/src'
    networks:
      - albatross
    volumes:
      - ./:/mpb
    tty: true
    command: python -m flask run --host=0.0.0.0

networks:
  albatross:
    driver: bridge