#!/usr/bin/env bash
set -o errexit

# Check the pyproject.toml is formatted correctly
echo "formatting pyproject.toml"
toml-sort --in-place pyproject.toml

echo "Running black"
black $SRC_PATH $TEST_PATH

echo "Running ruff"
# Auto fix linting issues
ruff check  "${SRC_PATH}" "${TEST_PATH}" --fix

# Run formatting over files
ruff format "${SRC_PATH}" "${TEST_PATH}"